Update environment.prod.ts
Cannot use require() for ES6 import, either import file as
const packageJson = require('../../package.json') 
or
import * as packageJson from '../../package.json'.

Encountered error when running app with previous import: 
ERROR in src/environments/environment.prod.ts(1,1): error TS1202: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.